[tool.poetry.repositories]

[tool.poetry]
name = "omicron"
version = "0.4.0"
description = ""
authors = ["jieyu <code@jieyu.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.3"
sh = "^1.14.1"
asyncpg = "^0.21.0"
gino = "^1.0.1"
SQLAlchemy = "^1.3.20"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
