[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
[tool.poetry]
name = "zillionare-omicron"
version = "0.3.0"
description = "Core library for Zillionare"
authors = ["jieyu <code@jieyu.ai>"]
license = "MIT"
packages = [
    { include = "omicron"}
]
include = ["README.rst", "LICENSE", "HISTORY.rst", "AUTHORS.rst", "CONTRIBUTING.rst"]

[tool.poetry.dependencies]
python = "^3.8"
cfg4py = "^0"
arrow = "^0.15"
numpy = "^1.19.4"
aioredis = "^1.3.1"
numba = "^0.49.1"
SQLAlchemy = "^1.3.20"
gino = "^1.0.1"
asyncpg = "^0.21.0"
aiohttp = "^3.7.2"
sh = "^1.14.1"
pyemit = "^0.4.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
tox = "^3.20.1"
coverage = "^5.3"
Sphinx = "^3.2.0"
black = "^20.8b1"
pre-commit = "^2.8.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
doc8 = "^0.8.1"
recommonmark = "^0.6.0"
m2r = "^0.2.1"
myst-parser = "^0.12.10"
virtualenv = "^20.1.0"
packaging = "^20.4"
omega = {path = "/c/workspace/omega"}
zillionare-omega-adaptors-jq = "^0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''